### ISSUE TITLE
Computing the drift loss cone/L* at very low L values

### ISSUE THREAD

**Issue by claudepi** [PRBEM/IRBEM#10]
I wanted to capture something here that I spent a long-ish time looking at recently, in case it is useful for someone. I'm not advocating that this is something that needs to be addressed or resolved. It's probably not really a bug, but rather just a feature/limitation of the drift_bounce_orbit routine.  I should also mention that I don't think I ever totally understood the issue at hand, but believe it is generally related to gridding and computing quantities along field lines and in azimuth (i.e., a general problem with this approach, which is what is done in IRBEM/drift_bounce_orbit). 

The image below illustrates what I found. I have computed the bounce loss cone (BLC) angle on a fixed Lm/geographic longitude grid for a dipole field (panel (a)) and for the IGRF+OP77Q field from IRBEM (panel (b)). Panel (c) shows my calculation of the drift loss cone (DLC) angle on this same grid/field model. My technique is to trace field lines using drift_bounce_orbit for different local pitch angle values and then to use a bisection method to find the pitch angle at which L* becomes undefined (this is the local DLC angle). However, when I compare this approach with the "true" DLC angle, computed _a posteriori_ by taking the maximum of the BLC over all longitudes (i.e., taking the max of panel (b)), I don't get the same answer. This is shown in panel (d). Panel (e) shows the difference between these two DLC approaches, where errors are on the order of 5% near Lm=1.1. Panel (f) shows the BLC profile vs longitude at Lm=1.1 and panel (g) shows my calculation of the DLC compared with the true value at Lm=1.1. I am only able to calculate the correct value in a small longitude range near -60 degrees. 

![dlc](https://user-images.githubusercontent.com/63437576/119843351-5559a700-bebc-11eb-8f11-9fdab83f70cc.png)

I experimented extensively with changing the resolution of the L* calculation in drift_bounce_orbit (e.g., increasing it to the maximum possible number of azimuths) and other parameters, but nothing helped. I even hacked the library and hardwired in a very fine azimuthal grid, but this didn't help either. 

It is certainly possible that there is an error in my approach/technique. 

@tpoiii suggested to me that maybe LANLGEOMAG does this type of thing better than IRBEM (I don't have any experience with LANLGEOMAG).

**Comment by drsteve** [comment]
Just noting that I've seen this but haven't had any time to think about any of it. Happy to help out if you decide to look at [LANLGeoMag](https://github.com/drsteve/LANLGeoMag) - it'd be nice to have a comparison here (_a la_ the Albert et al. LCDS paper)

**Comment by claudepi** [comment]
Thanks Steve. I think I will eventually find some time to return to this question, at which time I will probably investigate with LANLGeoMag. I will follow up then.

**Comment by claudepi** [comment]
Closing the loop here. I took alternate approach to this DLC angle calculation and I get a better result. Instead of using the bisection method described above, here I calculate local DLC/BLC angles using the model field values of Blocal, B100, and B100' as defined in Selesnick, 2015 [[doi: 10.1002/2015JA021387](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015JA021387)]. 

![irbem_dlc_github_new](https://user-images.githubusercontent.com/63437576/158262126-8649c857-34a9-4062-af2d-e8d8c7420f69.png)

That little bump near the SAA (longitudes ~ -90 to -45 deg) in the figures in the first the post is now gone, at the expense of some noise that does not appear when the bisection method is used e.g., panel (c), the vertical striations that appear at each of the 25 azimuths hardwired into IRBEM. With the bisection method you can compute the DLC angle to a desired accuracy, so it is smoother in general (though gets hung up near the SAA, as noted above in the first post).  

I'm not sure why I tried the bisection thing in the first place - I think someone suggested it and I got excited because doing bisections is cool. But I find that this new approach gives a better result in general, so I am using that going forward. 

I note that the errors in the new approach below L~1.1 are mostly due to the fact that full drift shells cannot be computed there and so some quality control stuff has to be done. Basically, one can just assume that alpha_dlc is 90 degrees there.
