### ISSUE TITLE
python wrappers in conda env

### ISSUE THREAD

**Issue by claudepi** [PRBEM/IRBEM#14]
@mshumko Do you have any experience installing the python wrappers when using conda environments? I ask because I am installing IRBEM on a new linux system and I always get nervous about using pip to install packages alongside conda. I was following your instructions for the python wrappers ("python3 -m pip install --user -e .") but I'm wondering whether I should do that inside of my standard conda env, or outside of it. Thoughts?

**Comment by AntoineBrunet** [comment]
I think providing a conda-forge package for IRBEM and the python wrapper
would be a nice milestone and solve this issue nicely. I can have a look at
it but of you want to do it @mshumko, do not hesitate.

**Comment by mshumko** [comment]
@claudepi I am glad to hear that it installed without problems. 

I purposefully kept the external packages to just numpy and scipy. 

For future visitors: I've seen scipy break when it was installed by pip in a conda environment. I don't have a great solution to this except to only install scipy using conda.
