### ISSUE TITLE
Type mismatch when installing library on Mac

### ISSUE THREAD

**Issue by sanjaychepu** [PRBEM/IRBEM#15]
I'm a student of Allison Jaynes at Iowa trying to install on my Mac.
When I run ```make OS=osx ENV=gnu64 all``` I get many (~100) Type mismatch errors from passing INTEGER(8) to INTEGER(4) (and a rank mismatch as well). I did double-check that I have a 64-bit computer that I'm trying to make a 64-bit library on and that my compiler seems to be working.

### Minimal example to reproduce issue:

```
git clone https://github.com/PRBEM/IRBEM.git
cd IRBEM/
make OS=osx env=gnu64 all
```

### Error message:

This first message was repeated almost identically at many different places
```
   15 |      &%VAL(argv(28)),%VAL(argv(29)))
      |                                    1
Error: Type mismatch in argument 'idet' at (1); passed INTEGER(8) to INTEGER(4)
```
```
   35 |        call find_bm_nalpha (xx0,1,alpha,Bposit,Bmir,xmin)
      |                                  1
Error: Rank mismatch in argument 'alpha' at (1) (rank-1 and scalar)
```

### OS, IRBEM version, and compiler version information:

OS: Mac OS X 10.14.6
short hash: 614a227
gfortran: GNU Fortran (Homebrew GCC 10.2.0_4) 10.2.0

**Comment by AntoineBrunet** [comment]
Hi,
Thanks for raising this issue. So this is linked to the IDL wrappers of the library, and there is a lot of issues with the wrapper implementation with gfortran (on Linux as well, albeit it only produces warnings). I am looking into this, but I think it would require significant effort to properly fix.

As you are using gfortran anyway, you could try to compile the library using OS=linux and ENV=gnu64, I guess it should work properly.

**Comment by sanjaychepu** [comment]
Thanks for your help! When I tried it with ENV=gnu64 it gave the same error, but when I used ENV=gfortran64 it worked.
