### ISSUE TITLE
Add Windows and OSx compilation configurations and CI tests.

### ISSUE THREAD

**Issue by AntoineBrunet** [PRBEM/IRBEM#26]
As discussed in PR #22 , we need to add compilation configurations for Windows and OSX and the corresponding CI validation chains.

We can use the old configuration options from the previous Makefile, but we need someone with the corresponding environments to do it and test it properly.

**Comment by mshumko** [comment]
I just received a Windows computer with a Fortran compiler so I will begin to tackle this soon.

As for OSX, I found that GitHub Actions have global variables, one of which is [GITHUB_ACTIONS](https://docs.github.com/en/actions/learn-github-actions/environment-variables#:~:text=in%20composite%20actions.-,GITHUB_ACTIONS,-Always%20set%20to) that we can use to differentiate the GitHub CI environment from a local one.

I got a plan to implement the OSX CI so I'll hopefully have a PR soon.  What [GitHub Actions gfortran compiler](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#:~:text=GNU%20Fortran%20Homebrew,gfortran%2D11%20alias ) should I use?

**Comment by mshumko** [comment]
Addressed by PR #33
