### ISSUE TITLE
Building error on Ubuntu: myOwnMagField No such file or directory

### ISSUE THREAD

**Issue by mshumko** [PRBEM/IRBEM#3]
When I run ```make OS=linux64 ENV=gnu64 all``` the first time I get an error that `myOwnMagField*.f` is not found. The makefile is trying to move files that match the pattern `myOwnMagField*.f` from the `./src_desp/` directory. It also looks like there are remnants of sourceforge  in the makefile.

After I run this command, `myOwnMagField.f` and `myOwnMagField_init.f` are now in the `/IRBEM/` directory. I experimented by running the ```make OS=linux64 ENV=gnu64 all``` command again and I got a similar error (see the two traces below).

Is `myOwnMagField.f` a dummy file? Perhaps it should be placed in the `./source/` or the `./example/` directories (or somewhere else).

### Minimal example to reproduce issue:

```shell
git clone https://github.com/PRBEM/IRBEM.git
cd IRBEM
make OS=linux64 ENV=gnu64 all
```

### Error message:

When I run the `make...all` command the first time, IRBEM moves `myOwnMagField.f` to `IRBEM/`.
```shell
/bin/sh: 1: [[: not found
/bin/sh: 1: [[: not found
http://irbem.svn.sourceforge.net/svnroot/irbem, http://irbem.svn.sourceforge.net/svnroot/irbem/???, NonSVN, Unknown
mv: cannot stat './src_desp/myOwnMagField*.f': No such file or directory
make: *** [Makefile:466: myOwnMagField1] Error 1
```

Now when I run `make...all` command again, I get a slightly different error:
```shell
http://irbem.svn.sourceforge.net/svnroot/irbem, http://irbem.svn.sourceforge.net/svnroot/irbem/???, NonSVN, Unknown
mv: cannot stat './source/myOwnMagField*.f': No such file or directory
mv: cannot stat './src_desp/myOwnMagField*.f': No such file or directory
make: *** [Makefile:466: myOwnMagField1] Error 1 
```

### OS, IRBEM version, and compiler version information:

OS:
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana

IRBEM commit hash:
431ebea

gfortran version:
GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by AntoineBrunet** [comment]
Ok I think there are three issues here:
 - myOwnMagField is not properly managed. I am not sure what Sébastien was aiming for in the Makefile in the two targets that fail.
 - There are remnants of the svn repository to manage the versions numbers, and we should migrate this part to be compatible with the new git repository.
 - The first two lines are actually shell errors. I think this is a bash-specific syntax, but at least on debian-like distributions /bin/sh is not bash-compatible. I think we should correct the Makefile to only use POSIX syntax.

I'll create two separate issues for the last two points, as I think they are farely separate matters.
