### ISSUE TITLE
Incorrect number of arguments in IDL wrapper for shielddose2

### ISSUE THREAD

**Issue by czqqpw** [PRBEM/IRBEM#34]
the shieldose2.f can work in intel fortran complier, but when use the libirbem.dll in idl, it cannot work and will shutdown the idl, unless delete these 3 lines of totdose's calculation and rebuild the dll. it seems you cannot send any value out of the function by totdose.

```
K=1
      J=1
      M=1
      DO I=1,IMAX
         ProtDose(I,K) = DOSP(I,J)
         SolDose(I,K) = DOSOL(I,J)
         ElecDose(I,K) = DOSE(I,M,J)
         BremDose(I,K) = DOSB(I,M,J)
         !TotDose(I,K)=DOSP(I,J)+DOSOL(I,J)+DOSE(I,M,J)+DOSB(I,M,J)
      ENDDO
      K=2
      J=1
      M=2
      DO I=1,IMAX
         ProtDose(I,K) = DOSP(I,J)
         SolDose(I,K) = DOSOL(I,J)
         ElecDose(I,K) = DOSE(I,M,J)
         BremDose(I,K) = DOSB(I,M,J)
         !TotDose(I,K)=DOSP(I,J)+DOSOL(I,J)+DOSE(I,M,J)+DOSB(I,M,J)
      ENDDO
      K=3
      J=2
      M=1
      DO I=1,IMAX
         ProtDose(I,K) = DOSP(I,J)
         SolDose(I,K) = DOSOL(I,J);
         ElecDose(I,K) = DOSE(I,M,J)
         BremDose(I,K) = DOSB(I,M,J)
        ! TotDose(I,K)=DOSP(I,J)+DOSOL(I,J)+DOSE(I,M,J)+DOSB(I,M,J)
      ENDDO
```

### OS, IRBEM version, and compiler version information:
OS: windows11
IRBEM version: 
gfortran: 12.1.0

**Comment by drsteve** [comment]
Thanks for the report. My guess (though I can't test on IDL) is that the wrapper function is expecting the wrong number of arguments.

Can I ask you to try uncommenting the lines with `TotDose`, and then changing [line 144 in the IDL wrapper source](https://github.com/PRBEM/IRBEM/blob/d876aec6324bc5c49afb5a2bb5b885cab76fbb91/source/idl_wrappers.c#L144) to read
```
IDL_WRAPPER(shieldose2idl,shieldose2,29)
```

Please let us know if that works!

**Comment by czqqpw** [comment]
the correction is worked, now the dll will not shut down the idl and can get correct result. thanks. 
 i found another problem in Alexeev2000.f
`subroutine a2000(ro,v,bimf,dst,al,x,bm,ifail)`
`DIMENSION x(3), bm(3), par(10), bb(7,3), bimf(3)
      REAL*8   a2000_ut
      INTEGER*4 a2000_iyear,a2000_imonth,a2000_iday,ifail`
for example, the bimf(3) is used to transmit values, it is declared by DIMENSION, so its type is real.
the subroutine champ in init_noveau.f calls a2000, in its calling the bimf(3) is BxSM(3), and its type is real*8. i guess beacuse of this difference, the value cannot be transmitted correctly, and the a2000 will return invalid values.
there are other variables in a2000 have the same problem, including ro, v, bm, x, and several subroutines are the same. 
the solution is add declaring below the DIMENSION or COMMON, just like
`DIMENSION x(3), bm(3), par(10), bb(7,3), bimf(3)`
`REAL*8   a2000_ut,bimf`

**Comment by drsteve** [comment]
Thanks for the update and for the additional report. I'll submit a pull request to get this fixed shortly.

I've started a new issue tracker for the Alexeev model concerns, someone will take a look soon.
