### ISSUE TITLE
Request python version for  drift_bounce_orbit

### ISSUE THREAD

**Issue by PluckZK** [PRBEM/IRBEM#47]
In a python environment, I want to calculate drift-bounce averages along the drift-bounce orbit.
However I found that there is currently no support for this feature.

https://github.com/PRBEM/IRBEM/blob/29354bd5ed1835cd4a166b0e33fda84e2314279d/python/IRBEM/IRBEM.py#L239

Can you please add support for this feature? thank you very much

**Comment by AntoineBrunet** [comment]
As the PR #48 has been merged, I'll close this issue as completed. @PluckZK if you have any issue with the implementation feel free to open another issue.
